server:
  port: 30011
  ssl:
    enabled: true
    protocol: TLS
    key-store: classpath:keystore.p12
    key-store-password:
    key-alias:
    key-password:
    enabled-protocols:
      - TLSv1.2
      - TLSv1.3
    ciphers:
      - TLS_AES_256_GCM_SHA384
      - TLS_CHACHA20_POLY1305_SHA256
      - TLS_AES_128_GCM_SHA256
      - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
      - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
      - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
      - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
      - TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
      - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
      - TLS_RSA_WITH_AES_256_GCM_SHA384
      - TLS_RSA_WITH_AES_128_GCM_SHA256
      - TLS_RSA_WITH_AES_256_CBC_SHA
      - TLS_RSA_WITH_AES_128_CBC_SHA
      - TLS_RSA_WITH_3DES_EDE_CBC_SHA

parameters:
  client-config:
    min-supported-version: 84
    min-supported-version-name: 3.0.1
  game-config:
    default-tables-config-path: tables_config_prod.json
    drawing-player-inactivity-limit-seconds: 60
    words-pair-length-diff-factor: 0.3
    close-enough-answer-distance-factor: 0.3
    table-name-config:
      DEFAULT:
        prefix: "#"
        base-number: 100
      PUBLIC:
        prefix: "#"
        base-number: 200
      PRIVATE:
        prefix: "#"
        base-number: 300
  log-storage:
    path:
  words-storage:
    path:

logging:
  level:
    root: WARN
    com.ick.kalambury: INFO
